version: '3.1'
services:
  relay:
    image: node:14
    working_dir: /opt/app/
    ports:
      - 8080:8080
    command: node ./dist/index.js
    stop_grace_period: 15s
    environment:
      TZ: Asia/Ho_Chi_Minh
      NODE_ENV: testing
      HOST: 127.0.0.1
      PORT: 8080
      REDIS_URL: redis://127.0.0.1:6379/0
      REDIS_PREFIX: wc-bridge
      REDIS_MAXTTL: 86400
      RELAY_MODE: any
      SENTRY_DSN: 
      INTERNAL_ORIGINS: https://abc.com,https://xyz.com
    volumes:
      - /opt/projects/walletconnect-monorepo/servers/relay/:/opt/app/:Z
    healthcheck:
      test: ["CMD", "curl",  "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 5s
    restart: on-failure
