version: '3.9'

networks:
  default:

volumes:
  redis:
    name: 'redis-{{.Task.Slot}}'
  waku:
    name: 'waku-{{.Task.Slot}}'
  caddy_data:
  caddy_conf:

configs:
  caddyfile:
    file: ./Caddyfile

services:
  caddy:
    image: ${CADDY_IMAGE}
    deploy:
      mode: replicated
    # Port mode must be mode: host to allow access to the external ip
    configs:
      - source: caddyfile
        target: /config/Caddyfile
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - caddy_data:/data
      - caddy_conf:/config

  redis:
    image: 'redis:6-alpine'
    hostname: "redis.{{.Task.Slot}}"
    volumes:
      - redis:/data
    deploy:
      replicas: ${REPLICAS:-1}

  waku:
    image: ${WAKU_IMAGE}
    hostname: "waku.{{.Task.Slot}}"
    volumes:
      - waku:/mnt
    environment:
      SWARM_PEERS: "tasks.{{.Service.Name}}"
      STORE: "/ip4/138.197.189.151/tcp/60000/p2p/16Uiu2HAmF1iLV2KdC7YUj99YKoqCYWSiMBq34mdmQX28J8k4kqmn"

  relay:
    image: ${RELAY_IMAGE}
    hostname: "relay.{{.Task.Slot}}"
    environment:
      PORT: ${RELAY_PORT}
      REDIS_URL: "redis://redis.{{.Task.Slot}}:6379/0"
      WAKU_URL: "http://waku.{{.Task.Slot}}:8545"
